# Generated by Django 4.1.3 on 2023-04-02 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline')], default='OFF', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('max_members', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=events.models.create_default_author, on_delete=django.db.models.deletion.PROTECT, to='events.author')),
                ('members_list', models.ManyToManyField(blank=True, related_name='subscribess', to='events.author')),
                ('place', models.ForeignKey(default=events.models.create_default_place, on_delete=django.db.models.deletion.PROTECT, to='events.place')),
            ],
        ),
    ]
