# Generated by Django 4.1.3 on 2023-04-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
