version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py planner.wsgi
    volumes:
      - .:/code
    env_file:
      - ./config/.env
    networks:
      - internal_network

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
  external_network:
    external: true

volumes:
  db_data:
