# Generated by Django 4.1.3 on 2022-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_remove_event_category_event_maxregistered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='closed',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timeofend',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='MaxRegistered',
            new_name='max_members',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timeofstart',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='NumberOfRegistered',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline')], default='OFF', max_length=3),
        ),
    ]
