# Generated by Django 4.1.3 on 2022-12-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_members_list_alter_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members_list',
            field=models.ManyToManyField(related_name='subscribess', to='api.author'),
        ),
    ]
