# Generated by Django 4.1.3 on 2022-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_members_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members_list',
            field=models.ManyToManyField(blank=True, related_name='subscribess', to='api.author'),
        ),
    ]
