# Generated by Django 4.1.3 on 2022-12-03 17:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_members_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=api.models.create_default_author, on_delete=django.db.models.deletion.PROTECT, to='api.author'),
        ),
    ]
